drop  table product_category;
drop  table product;
-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS product_category
(
    id            BIGINT       NOT NULL primary key generated by default as identity,
    category_name VARCHAR(255) NULL DEFAULT NULL
    );

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS product
(
    id             BIGINT NOT NULL primary key generated by default as identity,
    sku            VARCHAR(255)   DEFAULT NULL,
    name           VARCHAR(255)   DEFAULT NULL,
    description    VARCHAR(255)   DEFAULT NULL,
    unit_price     DECIMAL(13, 2) DEFAULT NULL,
    image_url      VARCHAR(255)   DEFAULT NULL,
    active         bool        default true,
    units_in_stock int            DEFAULT NULL,
    date_created   timestamp      DEFAULT NULL,
    last_updated   timestamp      DEFAULT NULL,
    category_id    BIGINT NOT NULL references product_category (id)
    );


CREATE TABLE if not exists country
(
    id smallint primary key generated by default as identity NOT NULL,
    code varchar(2)   DEFAULT NULL,
    name varchar(255) DEFAULT NULL
    );

CREATE TABLE state
(
    id         smallint primary key generated by default as identity NOT NULL,
    name       varchar(255) DEFAULT NULL,
    country_id smallint references country (id) NOT NULL
);














-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------

--
-- Prep work
--
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS address;

--
-- Table structure for table  address
--
CREATE TABLE address (
                         id bigint NOT NULL generated by default as identity primary key ,
                         city varchar(255) DEFAULT NULL,
                         country varchar(255) DEFAULT NULL,
                         state varchar(255) DEFAULT NULL,
                         street varchar(255) DEFAULT NULL,
                         zip_code varchar(255) DEFAULT NULL
);

--
-- Table structure for table  customer
--
CREATE TABLE  customer
(
    id         bigint NOT NULL primary key generated by default as identity,
    first_name varchar(255) DEFAULT NULL,
    last_name  varchar(255) DEFAULT NULL,
    email      varchar(255) DEFAULT NULL
);

--
-- Table structure for table  orders
--
CREATE TABLE  orders  (
                          id  bigint NOT NULL generated by default as identity primary key ,
                          order_tracking_number  varchar(255) DEFAULT NULL,
                          total_price  decimal(19,2) DEFAULT NULL,
                          total_quantity  int DEFAULT NULL,
                          billing_address_id  bigint DEFAULT NULL,
                          customer_id  bigint DEFAULT NULL,
                          shipping_address_id  bigint DEFAULT NULL,
                          status  varchar(128) DEFAULT NULL,
                          date_created  timestamp DEFAULT NULL,
                          last_updated  timestamp DEFAULT NULL,
                          CONSTRAINT  FK_customer_id  FOREIGN KEY ( customer_id ) REFERENCES  customer  ( id ),
                          CONSTRAINT  FK_billing_address_id  FOREIGN KEY ( billing_address_id ) REFERENCES  address  ( id ),
                          CONSTRAINT  FK_shipping_address_id  FOREIGN KEY ( shipping_address_id ) REFERENCES  address  ( id )
) ;

--
-- Table structure for table  order_items
--
CREATE TABLE  order_item  (
                              id  bigint NOT NULL generated by default as identity primary key ,
                              image_url  varchar(255) DEFAULT NULL,
                              quantity  int DEFAULT NULL,
                              unit_price  decimal(19,2) DEFAULT NULL,
                              order_id  bigint DEFAULT NULL,
                              product_id  bigint DEFAULT NULL,
                              CONSTRAINT  FK_order_id  FOREIGN KEY ( order_id ) REFERENCES  orders  ( id ),
                              CONSTRAINT  FK_product_id  FOREIGN KEY ( product_id ) REFERENCES  product  ( id )
);

